### ISSUE TITLE
ui redesign

### ISSUE THREAD

**Issue by woelbit** [thomasmauerhofer/YAQ#10]
- redesign user interface (material design)
- logo

**Comment by AndrejMueller01** [comment]
![screenshot_20160605-001524](https://cloud.githubusercontent.com/assets/6002250/15802493/8fa402d0-2ab4-11e6-860d-fa228f735d10.png)
![screenshot_20160605-001528](https://cloud.githubusercontent.com/assets/6002250/15802494/8fa886ac-2ab4-11e6-978d-10aac9ee833a.png)
![screenshot_20160605-001534](https://cloud.githubusercontent.com/assets/6002250/15802495/8faad18c-2ab4-11e6-849f-2dc76045893c.png)
![screenshot_20160605-001541](https://cloud.githubusercontent.com/assets/6002250/15802496/8fae20a8-2ab4-11e6-82ea-d986b9123693.png)
![screenshot_20160605-001544](https://cloud.githubusercontent.com/assets/6002250/15802497/8fb13018-2ab4-11e6-9b05-7dc640e7cd0f.png)
![screenshot_20160605-001554](https://cloud.githubusercontent.com/assets/6002250/15802498/8fb577a4-2ab4-11e6-8a03-a88d50acbd8e.png)
![screenshot_20160605-001556](https://cloud.githubusercontent.com/assets/6002250/15802499/8fbe22fa-2ab4-11e6-8019-a8420b1f62cb.png)
![screenshot_20160605-001605](https://cloud.githubusercontent.com/assets/6002250/15802500/8fc2ef74-2ab4-11e6-9fd3-cfbac9702553.png)
![screenshot_20160605-001615](https://cloud.githubusercontent.com/assets/6002250/15802501/8fc5d4d2-2ab4-11e6-8c8c-8de6566660fc.png)
![screenshot_20160605-001628](https://cloud.githubusercontent.com/assets/6002250/15802502/8fc8f590-2ab4-11e6-9759-aba8d36d2d8f.png)
![screenshot_20160605-001632](https://cloud.githubusercontent.com/assets/6002250/15802503/8fcd04b4-2ab4-11e6-8c58-4383e26c92d2.png)
![screenshot_20160605-001637](https://cloud.githubusercontent.com/assets/6002250/15802504/8fd28d9e-2ab4-11e6-9a4f-29c06cac2bf0.png)
