### ISSUE TITLE
Answer is clickable after countdown is over

### ISSUE THREAD

**Issue by AndrejMueller01** [thomasmauerhofer/YAQ#31]
- Wait until the question countdown is over.
- Click on a answer-button
  => The button turns gray, GUI bugs

**Comment by woelbit** [comment]
good catch

btw. we should not forget about the bug that causes a crash when clicking on an answer button **before** a question is shown

**Comment by woelbit** [comment]
fixed in 095a6f8bbb8fcd0bafe9cf37599191d628b82318
